### ISSUE TITLE
paySubmit wont return the payment event data

### ISSUE THREAD

**Issue by TreemboLuisDev** [derrmru/paypal-smart-button-react#1]
![image](https://user-images.githubusercontent.com/19478245/124827734-fd42a580-df3b-11eb-9029-83722060b54d.png)
The paySubmit prop wont return the event data, it outputs a console log with the data, but when I do paySubmit={(e)=>{console.log(e)}}, the e variable is undefined.

**Comment by derrmru** [comment]
Thanks @TreemboLuisDev - I have updated this for 1.0.7

The order event data is now passed to your paySubmit function - if you have any issues do get back to me
